SaleManagementSystem.WebApp/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SaleManagementSystem.Common;
using SaleManagementSystem.Model.DAL;

namespace SaleManagementSystem.WebApp.Controllers
{
    public class SalesController : Controller
    {
        private SaleManagementSystemEntities db = new SaleManagementSystemEntities();

        // GET: Sales
        public ActionResult Index(Guid? customerId, Guid? employeeId, string searchItemName, string searchCode, string sortOrder)
        {
            var sales = db.Sales.Include(s => s.Customer).Include(s => s.Employee).Include(s => s.Item)
                .Where(s => !s.IsDeleted);

            ViewBag.CustomerId = new SelectList(db.Customers.Where(c => !c.IsDeleted), "Id", "Name");
            ViewBag.EmployeeId = new SelectList(db.Employees.Where(c => !c.IsDeleted), "Id", "Name");
            ViewBag.searchItem = new SelectList(db.Items.Where(c => !c.IsDeleted), "Id", "Name");

            ViewBag.SaleCodeSortParm = String.IsNullOrEmpty(sortOrder) ? "saleCode_desc" : "";
            ViewBag.CustomerSortParm = sortOrder == "Customer" ? "Customer_desc" : "Customer";
            ViewBag.EmployeeSortParm = sortOrder == "Employee" ? "Employee_desc" : "Employee";
            ViewBag.ItemSortParm = sortOrder == "Item" ? "Item_desc" : "Item";
            ViewBag.PriceSortParm = sortOrder == "Price" ? "Price_desc" : "Price";
            ViewBag.QuantitySortParm = sortOrder == "Quantity" ? "Quantity_desc" : "Quantity";

            ViewBag.Customer = customerId;
            ViewBag.Employee = employeeId;
            ViewBag.Code = searchCode;
            ViewBag.Item = searchItemName;

            switch (sortOrder)
            {
                case "saleCode_desc":
                    sales = sales.OrderByDescending(s => s.SaleCode);
                    break;
                case "Customer":
                    sales = sales.OrderBy(s => s.Customer.Name);
                    break;
                case "Customer_desc":
                    sales = sales.OrderByDescending(s => s.Customer.Name);
                    break;
                case "Employee":
                    sales = sales.OrderBy(s => s.Employee.Name);
                    break;
                case "Employee_desc":
                    sales = sales.OrderByDescending(s => s.Employee.Name);
                    break;
                case "Item":
                    sales = sales.OrderBy(s => s.Item.Name);
                    break;
                case "Item_desc":
                    sales = sales.OrderByDescending(s => s.Item.Name);
                    break;
                case "Price":
                    sales = sales.OrderBy(s => s.Price);
                    break;
                case "Price_desc":
                    sales = sales.OrderByDescending(s => s.Price);
                    break;
                case "Quantity":
                    sales = sales.OrderBy(s => s.Quantity);
                    break;
                case "Quantity_desc":
                    sales = sales.OrderByDescending(s => s.Quantity);
                    break;
                default:
                    sales = sales.OrderBy(s => s.SaleCode);
                    break;
            }

            var result = new List<Sale>();

            if (!String.IsNullOrEmpty(searchItemName))
            {
                string searchString = StringHelpers.ConvertToUnSign(searchItemName).ToLower();
                result = sales.ToList().FindAll(
                    delegate (Sale s)
                    {
                        if ((StringHelpers.ConvertToUnSign(s.Item.Name.ToLower()).Contains(searchString)))
                            return true;
                        else
                            return false;
                    }
                );
            }
            else
            {
                result = sales.ToList();
            }
            if (!String.IsNullOrEmpty(searchCode))
            {
                result = result.Where(s => s.SaleCode.Contains(searchCode)).ToList();
            }
            if (customerId != null)
            {
                result = result.Where(s => s.CustomerId == customerId).ToList();
            }
            if (employeeId != null)
            {
                result = result.Where(s => s.EmployeeId == employeeId).ToList();
            }
            return View(result);
        }

        // GET: Sales/Create
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers.Where(s => !s.IsDeleted), "Id", "Name");
            ViewBag.EmployeeId = new SelectList(db.Employees.Where(s => !s.IsDeleted), "Id", "Name");
            ViewBag.ItemId = new SelectList(db.Items.Where(s => !s.IsDeleted), "Id", "Name");
            return View();
        }

        // POST: Sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EmployeeId,CustomerId,SaleCode,Unit,Price,ItemId,Quantity,IsDeleted,InsAt,InsBy,UpdAt,UpdBy")] Sale sale)
        {
            AuditTable.InsertAuditFields(sale);
            //sale.SaleCode = "GroupOne-" + DateTime.Now.ToString("MMddyyyy-HHmm");
            if (ModelState.IsValid)
            {
                sale.Id = Guid.NewGuid();
                db.Sales.Add(sale);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CustomerId = new SelectList(db.Customers.Where(s => !s.IsDeleted), "Id", "Name", sale.CustomerId);
            ViewBag.EmployeeId = new SelectList(db.Employees.Where(s => !s.IsDeleted), "Id", "Name", sale.EmployeeId);
            ViewBag.ItemId = new SelectList(db.Items.Where(s => !s.IsDeleted), "Id", "Name", sale.ItemId);
            return View(sale);
        }

        // GET: Sales/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers.Where(s => !s.IsDeleted), "Id", "Name", sale.CustomerId);
            ViewBag.EmployeeId = new SelectList(db.Employees.Where(s => !s.IsDeleted), "Id", "Name", sale.EmployeeId);
            ViewBag.ItemId = new SelectList(db.Items.Where(s => !s.IsDeleted), "Id", "Name", sale.ItemId);
            return View(sale);
        }

        // POST: Sales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EmployeeId,CustomerId,SaleCode,Unit,Price,ItemId,Quantity,IsDeleted,InsAt,InsBy,UpdAt,UpdBy")] Sale sale)
        {
            AuditTable.UpdateAuditFields(sale);
            if (ModelState.IsValid)
            {
                db.Entry(sale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CustomerId = new SelectList(db.Customers.Where(s => !s.IsDeleted), "Id", "Name", sale.CustomerId);
            ViewBag.EmployeeId = new SelectList(db.Employees.Where(s => !s.IsDeleted), "Id", "Name", sale.EmployeeId);
            ViewBag.ItemId = new SelectList(db.Items.Where(s => !s.IsDeleted), "Id", "Name", sale.ItemId);
            return View(sale);
        }

        // GET: Sales/Delete/5
        public ActionResult Delete(Guid? id)
        {
            var entityExist = db.Deliveries.Where(s => s.SaleId == id && !s.IsDeleted).FirstOrDefault();
            if (entityExist != null)
            {
                return PartialView("_Delete");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Sale sale = db.Sales.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
        }

        // POST: Sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Sale sale = db.Sales.Find(id);
            sale.IsDeleted = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SaleManagementSystem.WebApp/Controllers/_ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SaleManagementSystem.Common;
using SaleManagementSystem.Model.DAL;

namespace SaleManagementSystem.WebApp.Controllers
{
    public class _ItemsController : Controller
    {
        private SaleManagementSystemEntities db = new SaleManagementSystemEntities();

        // GET: _Items
        public ActionResult Index(string searchName, string searchMinAmount, string searchMaxAmount, string searchMinDate, string searchMaxDate, string sortOrder)
        {
            var items = db.Items.Where(i => !i.IsDeleted);

            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Expired_Date" ? "Expired_Date_desc" : "Expired_Date";
            ViewBag.AmountSortParm = sortOrder == "Amount" ? "Amount_desc" : "Amount";

            ViewBag.Name = searchName;
            ViewBag.MinAmount = searchMinAmount;
            ViewBag.MaxAmount = searchMaxAmount;
            ViewBag.MinDate = searchMinDate;
            ViewBag.MaxDate = searchMaxDate;

            switch (sortOrder)
            {
                case "name_desc":
                    items = items.OrderByDescending(s => s.Name);
                    break;
                case "Expired_Date":
                    items = items.OrderBy(s => s.DateExpired);
                    break;
                case "Expired_Date_desc":
                    items = items.OrderByDescending(s => s.DateExpired);
                    break;
                case "Amount":
                    items = items.OrderBy(s => s.Amount);
                    break;
                case "Amount_desc":
                    items = items.OrderByDescending(s => s.Amount);
                    break;
                default:
                    items = items.OrderBy(s => s.Name);
                    break;
            }

            var result = new List<Item>();

            if (!String.IsNullOrEmpty(searchName))
            {
                string searchString = StringHelpers.ConvertToUnSign(searchName).ToLower();
                result = items.ToList().FindAll(
                    delegate (Item i)
                    {
                        if ((StringHelpers.ConvertToUnSign(i.Name.ToLower()).Contains(searchString)))
                            return true;
                        else
                            return false;
                    }
                );
            }
            else
            {
                result = items.ToList();
            }
            if (!String.IsNullOrEmpty(searchMinAmount))
            {
                Decimal minAmount = Convert.ToDecimal(searchMinAmount);
                result = result.Where(s => s.Amount >= minAmount).ToList();
            }
            if (!String.IsNullOrEmpty(searchMaxAmount))
            {
                Decimal maxAmount = Convert.ToDecimal(searchMaxAmount);
                result = result.Where(s => s.Amount <= maxAmount).ToList();
            }
            if (!String.IsNullOrEmpty(searchMinDate))
            {
                DateTime fromDate = Convert.ToDateTime(searchMinDate);
                result = result.Where(s => s.DateExpired >= fromDate).ToList();
            }
            if (!String.IsNullOrEmpty(searchMaxDate))
            {
                DateTime toDate = Convert.ToDateTime(searchMaxDate);
                result = result.Where(s => s.DateExpired <= toDate).ToList();
            }
            return View(result);
        }
        //POST: Check Duplicate return Json
        public JsonResult CheckName(string Name, Guid? Id)
        {
            return Json(!db.Items.Any(x => x.Name == Name && x.Id != Id && !x.IsDeleted), JsonRequestBehavior.AllowGet);
        }
        // GET: _Items/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: _Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Unit,Amount,DateExpired,IsDeleted,InsAt,InsBy,UpdAt,UpdBy")] Item item)
        {
            AuditTable.InsertAuditFields(item);
            if (ModelState.IsValid)
            {
                item.Id = Guid.NewGuid();
                db.Items.Add(item);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: _Items/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: _Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Unit,Amount,DateExpired,IsDeleted,InsAt,InsBy,UpdAt,UpdBy")] Item item)
        {
            AuditTable.UpdateAuditFields(item);
            if (ModelState.IsValid)
            {
                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(item);
        }

        // GET: _Items/Delete/5
        public ActionResult Delete(Guid? id)
        {
            var entityExist1 = db.MenuItems.Where(s => s.ItemId == id && !s.IsDeleted).FirstOrDefault();
            var entityExist2 = db.Properties.Where(s => s.ItemId == id && !s.IsDeleted).FirstOrDefault();
            var entityExist3 = db.Sales.Where(s => s.ItemId == id && !s.IsDeleted).FirstOrDefault();
            if (entityExist1 != null || entityExist2 != null || entityExist3 != null)
            {
                return PartialView("_Delete");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Item item = db.Items.Find(id);
            if (item == null)
            {
                return HttpNotFound();
            }
            return View(item);
        }

        // POST: _Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Item item = db.Items.Find(id);
            item.IsDeleted = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SaleManagementSystem.WebApp/Views/Shared/_Delete.cshtml
@{
    Layout = null;
}

<div class="modal fade" id="MyModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="MyModal">This record can’t delete because it was been used to another places!</h4>
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="form-actions no-color text-center">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Cancel</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

SaleManagementSystem.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sale Management System</title>
    <link href="~/if_dribbble_2400860.png" rel="shortcut icon" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css">
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script>
        // Hàm khởi tạo đồng hồ
        function startTime() {
            var today = new Date();
            var d = today.getUTCDate(); var m = today.getUTCMonth() + 1;
            var y = today.getFullYear().toString().substr(-2); var h = today.getHours();
            var M = today.getMinutes(); var s = today.getSeconds();
            h = checkTime(h); s = checkTime(s); M = checkTime(M);
            m = checkTime(m); d = checkTime(d);
            document.getElementById('day').innerHTML = d; document.getElementById('month').innerHTML = m;
            document.getElementById('year').innerHTML = y; document.getElementById('Hour').innerHTML = h;
            document.getElementById('minute').innerHTML = M; document.getElementById('second').innerHTML = s;
            var t = setTimeout(function () {
                startTime();
            }, 500);
        }
        function checkTime(i) {
            if (i < 10) { i = "0" + i; }
            return i;
        }
    </script>
</head>

<body id="page-top" onload="startTime()">
    <nav class="navbar navbar-expand navbar-dark static-top" style="background: #025215; box-shadow: 0px 0px 2px 2px;">
        <button class="btn btn-link btn-sm text-white order-1 order-sm-0" id="sidebarToggle" href="#">
            <i class="fas fa-bars"></i>
        </button>
        <a class="navbar-brand ml-2" href="@Url.Action("Index","Home")"><b>Group One</b></a>

        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
            <ul class="navbar-nav ml-auto ml-md-0">
                <li class="nav-item text-light mr-4 mt-1">
                    <b id="Hour" class="text-center"></b> :
                    <b id="minute" class="text-center"></b> :
                    <b id="second" class="text-center"></b>
                </li>
                <li class="nav-item">
                    <b id="day" class="text-dark mr-3 text-center" style="display: block; width: 30px; height: 30px; line-height: 30px; background: white; border-radius: 100%"></b>
                </li>
                <li class="nav-item">
                    <b id="month" class="text-dark mr-3 text-center" style="display: block; width: 30px; height: 30px; line-height: 30px; background: white; border-radius: 100%"></b>
                </li>
                <li class="nav-item">
                    <b id="year" class="text-dark mr-3 text-center" style="display: block; width: 30px; height: 30px; line-height: 30px; background: white; border-radius: 100%"></b>
                </li>
            </ul>
        </form>
    </nav>

    <div id="wrapper">
        <!-- Sidebar -->
        <ul class="sidebar navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Customers")">
                    <i class="fas fa-users"></i>
                    <span class="ml-1">Customer</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Employees")">
                    <i class="fab fa-jenkins"></i>
                    <span class="ml-1">Employee</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Suppliers")">
                    <i class="fas fa-house-damage"></i>
                    <span class="ml-1">Supplier</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Sales")">
                    <i class="fas fa-piggy-bank"></i>
                    <span class="ml-1">Sale</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","_Items")">
                    <i class="fas fa-sitemap"></i>
                    <span class="ml-1">Item</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","MenuItems")">
                    <i class="fas fa-folder-minus"></i>
                    <span class="ml-1">Menu Item</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","PickUps")">
                    <i class="fas fa-truck-pickup"></i>
                    <span class="ml-1">Pick Up</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","_Properties")">
                    <i class="fas fa-tasks"></i>
                    <span class="ml-1">Property</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Purchases")">
                    <i class="far fa-credit-card"></i>
                    <span class="ml-1">Purchase</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Index","Deliveries")">
                    <i class="fas fa-dice-d6"></i>
                    <span class="ml-1">Delivery</span>
                </a>
            </li>
        </ul>

        <div id="content-wrapper">
            <div class="container-fluid">
                <!-- Breadcrumbs-->
                <ol class="breadcrumb" style="font-size: 20px; color: #025215;">
                    <b><li class="breadcrumb-item">@ViewBag.Title</li></b>
                </ol>
                <!-- Icon Cards-->
                @RenderBody()
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- Sticky Footer -->
    <footer class="sticky-footer mr-3" style="width: 81%;" >
        <div class="container my-auto">
            <div class="copyright text-center my-auto">
                <span>Copyright © 2018 - Group One - ASP.NET</span>
            </div>
        </div>
    </footer>

    <script src="~/Scripts/sb-admin.min.js"></script>
    <script src="~/Scripts/modal-dialog.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var url = window.location.pathname;
            var substr = url.split('/');
            var urlaspx = substr[substr.length - 1];
            $('#wrapper ul.sidebar li a').each(function () {
                if (this.href.indexOf(urlaspx) > 0) {
                    $(this).parent().addClass('active');
                }
            });
        });
    </script>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

SaleManagementSystem.WebApp/Views/Shared/_LayoutForModal.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sale Management System</title>
    <link href="~/if_dribbble_2400860.png" rel="shortcut icon" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css">
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body id="page-top" onload="startTime()">

    <div id="body-content">
        @RenderBody()
    </div>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.standalone.min.css" rel="stylesheet" />
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>